### ISSUE TITLE
无法访问面板

### ISSUE THREAD

**Issue by 1412188965** [vaxilu/x-ui#101]
家里闲置电脑装centos搭建x-ui无法访问面板，终端显示面板已经开启了
![屏幕截图 2021-09-20 163404](https://user-images.githubusercontent.com/62492913/133975326-99adb135-9053-4fa7-94d5-3764ca2a448e.png)

**Comment by mistercorea** [comment]
try curl localhost:65432 
or open 192.168.1.2:65432 on your browser

**Comment by 911502932** [comment]
centos没有关闭防火墙
