### ISSUE TITLE
x-ui cert and key to host

### ISSUE THREAD

**Issue by mistercorea** [vaxilu/x-ui#102]
任何由于自己的配置错误导致的情况，请自行解决，issues 只用于解决面板自身的 bug

如果你确定面板的功能实现有 bug，请尽可能提供更多更精确的描述信息、复现方法与复现结果等等，而不是草草一句话了事，这对于问题的解决没有帮助

提问的艺术: https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md

trying to use cert for different hosts and different ports by using sslforfree without CDN
used nginx type for cert and key to create and added to tls but it wont connect.

but without tls the configuration works.

**Comment by mistercorea** [comment]
Why was this closed can you explain how it is possible?

**Comment by vaxilu** [comment]
任何自身的配置问题请自行解决

**Comment by mistercorea** [comment]
I don't think it is a configuration. Can you explain which type of certs are suppose to use

I tried with apache and nginx
