### ISSUE TITLE
使用nginx反代之后，使用网址登录提示unknown data:

### ISSUE THREAD

**Issue by harrison-guo-chn** [vaxilu/x-ui#132]
使用ip+端口则正常，尝试过重新安装x-ui也不行
![image](https://user-images.githubusercontent.com/58265745/140594905-eef6f009-4f0c-466f-9b29-1f1918442242.png)
nginx配置
![image](https://user-images.githubusercontent.com/58265745/140594937-4eaa92c2-c511-42fb-a300-6a2d04cbb24a.png)
面板配置
![image](https://user-images.githubusercontent.com/58265745/140594966-e5611f49-a1a0-4097-aea1-edfe673697fc.png)

**Comment by askyzz** [comment]
> 使用ip+端口则正常，尝试过重新安装x-ui也不行 ![image](https://user-images.githubusercontent.com/58265745/140594905-eef6f009-4f0c-466f-9b29-1f1918442242.png) nginx配置 ![image](https://user-images.githubusercontent.com/58265745/140594937-4eaa92c2-c511-42fb-a300-6a2d04cbb24a.png) 面板配置 ![image](https://user-images.githubusercontent.com/58265745/140594966-e5611f49-a1a0-4097-aea1-edfe673697fc.png)
从上图看，已经安装成功了 不知道你说的不行是什么？

**Comment by harrison-guo-chn** [comment]
> > 使用ip+端口则正常，尝试过重新安装x-ui也不行 ![image](https://user-images.githubusercontent.com/58265745/140594905-eef6f009-4f0c-466f-9b29-1f1918442242.png) nginx配置 ![image](https://user-images.githubusercontent.com/58265745/140594937-4eaa92c2-c511-42fb-a300-6a2d04cbb24a.png) 面板配置 ![image](https://user-images.githubusercontent.com/58265745/140594966-e5611f49-a1a0-4097-aea1-edfe673697fc.png)
> > 从上图看，已经安装成功了 不知道你说的不行是什么？

就是图一的那个unknown data，用反代的网址登录就会提示这个问题，用ip加端口就不会。但是后来重启了几次小鸡之后就恢复了
