### ISSUE TITLE
x-ui 复制出来的节点，ws那里好像有点问题

### ISSUE THREAD

**Issue by zhaozhejun** [vaxilu/x-ui#48]
vless://11111-7537-4693-f346-0941cce0e9ce@twns.my03.com:11294?encryption=none&security=none&type=ws&**_path=%2ftw_**#tw11294

vless://11111-7537-4693-f346-0941cce0e9ce@twns.my03.com:11294?type=ws&security=none&**_path=%252Ftw_**#tw11294

如上，第一个可以导入任意软件中，第二个是 x-ui网页里复制出来的，path   好像utf8什么问题，，这个能修复吗？

**Comment by vaxilu** [comment]
fix
