### ISSUE TITLE
ubuntu安装后至只监听了v6端口 不自动监听v4端口 无法打开面板

### ISSUE THREAD

**Issue by kinysun** [vaxilu/x-ui#50]
![image](https://user-images.githubusercontent.com/23569018/128337752-6fa79dc0-eef5-48f4-b13c-44008a743ac5.png)
rt

**Comment by sprov065** [comment]
众所周知，::: ipv6 地址包含 0.0.0.0，基础的东西先弄明白了再问，此类问题统统跟防火墙相关
