### ISSUE TITLE
开启bbr提示：/dev/fd/63: line 1: 404:: command not found

### ISSUE THREAD

**Issue by jackom** [vaxilu/x-ui#65]
任何由于自己的配置错误导致的情况，请自行解决，issues 只用于解决面板自身的 bug

如果你确定面板的功能实现有 bug，请尽可能提供更多更精确的描述信息、复现方法与复现结果等等，而不是草草一句话了事，这对于问题的解决没有帮助

提问的艺术: https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md

<img width="522" alt="image" src="https://user-images.githubusercontent.com/5052960/130341434-123a9b55-a14d-40cc-bfe4-fef10db15757.png">

我是在墙外机器上安装的x-ui，机器是ubuntu 20系统的

**Comment by jukrb0x** [comment]
404是因为原来的安装bbr脚本的仓库挂了，可以尝试使用这个脚本安装：
```shell
bash <(curl -L -s https://raw.githubusercontent.com/teddysun/across/master/bbr.sh)
```

**Comment by vaxilu** [comment]
fix
