### ISSUE TITLE
忘记密码了该怎么搞

### ISSUE THREAD

**Issue by mazda1152** [vaxilu/x-ui#67]
/usr/local/x-ui/bin/config.json只有节点信息  没有登录密码信息

**Comment by Lenyu2020** [comment]
ssh登录vps  运行 x-ui 里面有密码重置选项的。

**Comment by oooh-name** [comment]
项目下面的 x-ui.sh  https://github.com/vaxilu/x-ui/blob/e8b0d2c839adf0f900bb271ffb45cb7dd9c363b7/x-ui.sh#L139-L150 有重置密码方法。
