### ISSUE TITLE
x-ui 配置fallback回落

### ISSUE THREAD

**Issue by wpyok500** [vaxilu/x-ui#70]
请问x-ui如何配置fallback，x-ui的vless协议配置后不起作用，@vaxilu 大佬能否给个说明文档。

其他协议vmess ,trojan是否支持回落，xray官方终极配置文件模板，支持其他协议fallback回落。
https://github.com/XTLS/Xray-examples/tree/main/VLESS-TCP-XTLS-WHATEVER

x-ui 配置
![image](https://user-images.githubusercontent.com/14154547/130539445-36880cf7-bfad-444c-9997-9d0ec08b26a8.png)
x-ui未接管443端口
![image](https://user-images.githubusercontent.com/14154547/130539514-8cdd784e-73b6-4c98-bbed-2a28ecc80e4a.png)

**Comment by vaxilu** [comment]
自行理解回落的含义
