### ISSUE TITLE
求面板的数据文件，类似于 /etc/v2-ui/v2-ui.db，方便一键备份和迁移

### ISSUE THREAD

**Issue by Hikpy** [vaxilu/x-ui#71]
任何由于自己的配置错误导致的情况，请自行解决，issues 只用于解决面板自身的 bug

如果你确定面板的功能实现有 bug，请尽可能提供更多更精确的描述信息、复现方法与复现结果等等，而不是草草一句话了事，这对于问题的解决没有帮助

提问的艺术: https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md

**Comment by oooh-name** [comment]
数据库文件不是默认在 /etc/x-ui/x-ui.db 吗？
