### ISSUE TITLE
求dalao给个443建伪站的ngnix配置文件抄抄作业

### ISSUE THREAD

**Issue by FaithAluten** [vaxilu/x-ui#72]
or有没有教程我去看看

**Comment by wpyok500** [comment]
wget -N --no-check-certificate -q "https://raw.githubusercontent.com/wpyok500/myxray_onekey/main/myxui.sh" && chmod +x myxui.sh && bash myxui.sh
x-ui 一键辅助安装脚本（nginx openssl acme 伪装站点 自动续签证书）
