### ISSUE TITLE
为何不能单端口复用？

### ISSUE THREAD

**Issue by GabrielGonGod** [vaxilu/x-ui#78]
如题，例如30000或者443端口，只能用于一个用户？多个用户只能开多个窗口吗

**Comment by wpyok500** [comment]
回落可以吧，不过目前x-ui缺少几个配置无法实现xray完整回落功能。

**Comment by GabrielGonGod** [comment]
> 回落可以吧，不过目前x-ui缺少几个配置无法实现xray完整回落功能。

抱歉，我才看到公告，原来是“难以实现”，谢谢回复。就是这样的话，要开好多端口。。。
