### ISSUE TITLE
http代理win10

### ISSUE THREAD

**Issue by noon2233** [vaxilu/x-ui#80]
http代理win10  不能用吗？
如图
![QQ截图20210829122558](https://user-images.githubusercontent.com/80038085/131238403-19d5cd1d-34dd-48d6-a350-3e74544e92ed.png)
![QQ截图20210829122635](https://user-images.githubusercontent.com/80038085/131238404-a1d04b0b-6e04-435c-bdf0-747d4135b717.png)

**Comment by o02** [comment]
所有类型在WIN10的这位置填了都不行，大哥，百度一下代理与VPN的区别吧。
