### ISSUE TITLE
80端口可以解决多开吗

### ISSUE THREAD

**Issue by lcybshwm** [vaxilu/x-ui#84]
多用户想使用同一个端口,但v2-ui一直不支持同端口多开,这个算个bug吧(小声bb),其他的v2ray安装都能不同userid,同一个80端口,应该也很好实现,只要同一个端口不改变连接类型吧

**Comment by karsacui** [comment]
可以x-ui多端口，然后nginx反向代理分流

**Comment by lcybshwm** [comment]
可能我表达的不够清楚,我的意思是80端口的用户,只能创建一个,如果说去掉这个限制就好了,可以通过v2ray的节点userid来达到多开效果吧,因为我手头搞一个免流节点的话,一般都是80节点,而80节点只能开一个用户,就达不到控制其他用户限制的目的了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vaxilu/x-ui"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月1日(星期三) 下午2:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [vaxilu/x-ui] 80端口可以解决多开吗 (#84)





 
可以x-ui多端口，然后nginx反向代理分流
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lcybshwm** [comment]
另外一个v2ray搭建的可以达到同端口多个用户,但是使用没有v2-ui方便,大佬你可以看一下这个bash <(curl -sL https://multi.netlify.app/v2ray.sh) --zh

**Comment by Andywei110** [comment]
![image](https://user-images.githubusercontent.com/59757806/132435631-3ac07057-ddea-4789-9265-827ec152a97f.png)
这样应该怎么设置宝塔nginx反代，用80端口
