### ISSUE TITLE
备注含“_”报错error

### ISSUE THREAD

**Issue by KeroseneW** [vaxilu/x-ui#88]
+ 入站列表添加时备注使用“_”导致xray报错直接出现error，面板运行正常，xray后台显示未运行，若直接删除则回复正常，无需重启。
+ 后续尝试“-”也是一样的问题，备注中单独或包含此字符均会出错

**Comment by vaxilu** [comment]
无法复现，跟备注无关系，自己看error里写了什么再判断

**Comment by KeroseneW** [comment]
就离谱，今天没问题了
