### ISSUE TITLE
一点点建议

### ISSUE THREAD

**Issue by Amos-Dan** [vaxilu/x-ui#98]
![1631869499(1)](https://user-images.githubusercontent.com/9195598/133756246-1b21f587-e50c-4bf1-aff7-0bb7cb7b839b.jpg)

另外可以加一个定时重启的功能吗？

**Comment by fuhailin** [comment]
请看Issues区置顶帖子，[功能建议点这里，不要开 issue](https://github.com/vaxilu/x-ui/issues/24)
